import type { Metadata } from "next"
import localFont from "next/font/local"
import "./globals.css"
import Link from "next/link"
import { Toaster } from "react-hot-toast"
import { Button } from "@/shared/components/Button.core"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900"
})
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className="h-full"
    >
      <head>
        <script src="https://unpkg.com/@phosphor-icons/web" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased text-slate-50 bg-slate-500 p-0 sm:p-4 text-sm`}
      >
        <div
          id="root"
          className="bg-slate-900 shadow-lg sm:rounded-xl max-w-[640px] mx-auto grid grid-rows-[auto_1fr_auto] min-h-full sm:min-h-[600px] relative"
        >
          <header className="flex p-4 border-b border-slate-700 justify-between items-center">
            <Link
              href="/"
              className="text-xl font-bold hover:opacity-50"
            >
              Store
            </Link>
            <Link href="/cart">
              <Button>
                <i className="ph-fill ph-shopping-cart"></i>
                Cart
              </Button>
            </Link>
          </header>
          <main className="">{children}</main>
          <footer className="h-16 grid place-items-center border-t border-slate-700">
            <Button>
              <Link href="https://mattrybin.com">Created by Matt Rybin</Link>
            </Button>
          </footer>
        </div>
        <Toaster />
      </body>
    </html>
  )
}
